name: Design
description: UI/UX or design related task
labels: ["design"]

body:
  - type: textarea
    id: description
    attributes:
      label: Design description
    validations:
      required: true

  - type: textarea
    id: spec
    attributes:
      label: Detailed spec / acceptance criteria
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      options:
        - medium
        - hard
    validations:
      required: true