name: Documentation
description: Documentation improvements or additions
labels: ["documentation"]

body:
  - type: textarea
    id: description
    attributes:
      label: Documentation description
    validations:
      required: true

  - type: textarea
    id: spec
    attributes:
      label: Detailed spec / acceptance criteria
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      options:
        - easy
        - medium
    validations:
      required: true